# Generated by Django 3.2.4 on 2021-07-18 10:36

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('jury', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_image', models.ImageField(upload_to='projects/')),
                ('project_title', models.TextField(max_length=200)),
                ('project_link', models.TextField()),
                ('project_description', tinymce.models.HTMLField()),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo_path',
            field=models.ImageField(upload_to='user_profiles/'),
        ),
    ]
