# Generated by Django 3.2.4 on 2021-07-18 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jury', '0003_auto_20210718_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-id']},
        ),
    ]
