# Generated by Django 3.2.4 on 2021-07-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jury', '0004_alter_userprofile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproject',
            name='project_link',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='project_title',
            field=models.CharField(max_length=200),
        ),
    ]
