# Generated by Django 3.2.4 on 2021-07-18 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jury', '0006_auto_20210718_1959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userproject',
            options={'ordering': ['-id']},
        ),
    ]
