# Generated by Django 3.2.4 on 2021-07-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jury', '0008_contentrating_designrating_usabilityrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproject',
            name='created_on',
            field=models.DateField(default='2021-07-18'),
        ),
    ]
