# Generated by Django 3.2.4 on 2021-07-19 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jury', '0009_userproject_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_rate', models.IntegerField(default=1)),
                ('usability_rate', models.IntegerField(default=1)),
                ('content_rate', models.IntegerField(default=1)),
                ('score_description', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jury.userproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='designrating',
            name='project',
        ),
        migrations.RemoveField(
            model_name='designrating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usabilityrating',
            name='project',
        ),
        migrations.RemoveField(
            model_name='usabilityrating',
            name='user',
        ),
        migrations.DeleteModel(
            name='ContentRating',
        ),
        migrations.DeleteModel(
            name='DesignRating',
        ),
        migrations.DeleteModel(
            name='UsabilityRating',
        ),
    ]
