# Generated by Django 3.2.4 on 2021-07-20 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jury', '0013_auto_20210720_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationrating',
            name='content_rate',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10, 'Must be less than or equal 10'), django.core.validators.MinValueValidator(1, 'cannot be less than 1')]),
        ),
        migrations.AlterField(
            model_name='applicationrating',
            name='design_rate',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10, 'Must be less than or equal 10'), django.core.validators.MinValueValidator(1, 'cannot be less than 1')]),
        ),
        migrations.AlterField(
            model_name='applicationrating',
            name='usability_rate',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10, 'Must be less than or equal 10'), django.core.validators.MinValueValidator(1, 'cannot be less than 1')]),
        ),
    ]
